### PR TITLE
Hierarchical modelling lab

### PR DESCRIPTION
**Pull request by theorashid**
Hi @elizavetasemenova,

Would you be able to check this outline and let me know what you think? The idea is the basic complete pooling, no pooling, partial pooling practical but applied to our health data. If we think there's enough time, I think we should add a section for trying a different prior on the variance parameter and running the Bayesian workflow (prior predictive, model fit, model checks).

Once we're happy with the outline, we can start working with the data and building a model.

I'm quite inundated at the moment with my thesis. If possible and if you have time, I would really appreciate some help with this part. Particularly getting a model we're happy with and all the code done – filling out the words around the code I am happy to do. This is probably the best place to communicate, so anyone else can see what we're working on.

Cheers and thanks,

Theo

### CODE REVIEW

**Comment by elizavetasemenova** [comment]
@theorashid fully agree on the outline, and happy to team up to work on the practical. I've never used Nimble though :) 

Is anyone planning to give a quick intro session as a part of the course? If the materials exist already, that's be useful for me to get up to speed.

**Comment by theorashid** [comment]
Intro to nimble?

I'll draft a quick data exploration and model section so you can see how it works. Then we can work on the model together. (at some point in the next couple of weeks)

**Comment by theorashid** [comment]
Hey @elizavetasemenova, sorry for the delay.

Here's an outline of how we could approach the task. I have isolated data from the final year and month of study. I am trying to estimate the (I think? But will check with Gary) standardised mortality ratio for each of the 107 provinces using a simple random effect.

I've fitted a basic partial pooling model in nimble. I hope this looks familiar to other PPLs you have used. You can also see how to take the nimble output and convert is to be used in stan-dev's posterior library. The code runs and rhat is fine, but I haven't done many checks beyond that.

If you'd like to play around with the data and the model, that would be great. Maybe try some different priors based on your knowledge, or a better model design. Or write the full pooling and no pooling models out. Then we can decide what goes in the rest of the practical and how you want to structure things to reinforce the content from your lecture.

Cheers and chat tomorrow,
Theo

Also @rmp15, this is the model that we'll use for the INLA software options practical. I suspect it won't take you long to make a script which does this in INLA with some diagnostics and prectictInterval etc. I can then flesh it out

**Comment by elizavetasemenova** [comment]
what I tried so far to install NIMBLE:

`install.packages("nimble")`

result: `Error: install of package 'igraph' failed [error code 1]`

`install.packages("igraph")`
result: `Error: install of package 'igraph' failed [error code 1]`


`devtools::install_github("igraph/rigraph")`
results: `Error: Failed to install 'igraph' from GitHub:
  ! System command 'R' failed`
  
  I am out of options

**Pull request merged**
