### PR TITLE
`Bayesian Workflow` with quatro

### PR DESCRIPTION
**Pull request by elizavetasemenova**

### CODE REVIEW

**Comment by theorashid** [comment]
So if you look at the presentation I recently committed, you can copy and paste the header https://github.com/rmp15/sharp_bayesian_environmental_health_2023/blob/main/lectures/software_options/software_options.qmd#L1-L24

I've made a fancy title page and used assets/style.csss to make a nice colour scheme.

–––

`pre-commit` is a system for checking commits/PRs so that they pass some style filters (called "hooks"). Basically, the idea is that you don't commit code which is formatted badly (you can make the hooks do other things too but I haven't done that here. If you look at https://github.com/rmp15/sharp_bayesian_environmental_health_2023/blob/main/.pre-commit-config.yaml, you can see the hooks I've used:
- remove trailing whitespace
- fix end of files
- make sure no really big files are added
- lint python files with ruff
- format python files with black
- format R files

The reason the workflow is failing for you is probably because you haven't installed pre-commit locally. Follow the installation instructions [here](https://pre-commit.com/#install) (either install it globally or install in a python env), then run `pre-commit install` to install the hooks. Then fix up your files locally with `pre-commit run --all-files` (you only need to do this once). Commit the diff and the workflow should work.

Now pre-commit is installed, any commit with these style errors should be automatically fixed.

**Comment by elizavetasemenova** [comment]
@theorashid 

pre-commit still isn't working. Here's my history:

```
conda create --name precommit_env
conda activate precommit_env
pip install pre-commit
conda install -c conda-forge pre-commit
pre-commit install
pre-commit run --all-files
 ```

Ended up with the error:

```
    Error: failed to retrieve package 'desc@1.4.1'
    In addition: There were 14 warnings (use warnings() to see them)
    Traceback (most recent calls last):
    8: renv::restore()
    7: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
    6: retrieve(packages)
    5: handler(package, renv_retrieve_impl(package))
    4: renv_retrieve_impl(package)
    3: renv_retrieve_repos(record)
    2: stopf("failed to retrieve package '%s'", renv_record_format_remote(record))
    1: stop(sprintf(fmt, ...), call. = call.)
    Execution halted
```

What's next?

**Comment by theorashid** [comment]
Looks like you have to install the Renv locally. Something like:

```
R
install.packages("renv")
install.packages("styler")
renv::restore()
```

This should install the packages in renv.lock and packages needed for the hook. If an error is thrown , just install the package it's asking about (in this case "desc")

If that doesn't work, maybe pre-commit is using the global R rather than the local one. This shouldn't happen but would be annoying. In this case, install the packages it's asking about in your global R setup

**Comment by elizavetasemenova** [comment]
I did 

```
R
install.packages("renv")
install.packages("styler")
renv::restore()
```
It ended up with the Error

```
Error: install of package 'Matrix' failed [error code 1]
Traceback (most recent calls last):
12: install.packages("Matrix")
11: install(pkgs)
10: renv_install_impl(records)
 9: renv_install_staged(records)
 8: renv_install_default(records)
 7: handler(package, renv_install_package(record))
 6: renv_install_package(record)
 5: withCallingHandlers(renv_install_package_impl(record), error = function(e) {
        vwritef("\tFAILED")
        writef(e$output)
    })
 4: renv_install_package_impl(record)
 3: r_cmd_install(package, path)
 2: r_exec_error(package, output, "install", status)
 1: stop(error)
```

I tried installing `Matrix` manually, without success.

> If that doesn't work, maybe pre-commit is using the global R rather than the local one. This shouldn't happen but would be annoying. In this case, install the packages it's asking about in your global R setup

How do I do that?

**Comment by theorashid** [comment]
Hmm. I’m quite confused why the Matrix package wouldn’t install. That seems to be some local issue with your R, maybe?I would just push whatever you have. I’ll tidy up your pre-commit formatting issues and we can debug the problem in person in New York :)Le 24 juin 2023 à 11:58, Elizaveta Semenova ***@***.***> a écrit :﻿
I did
R
install.packages("renv")
install.packages("styler")
renv::restore()

It ended up with the Error
Error: install of package 'Matrix' failed [error code 1]
Traceback (most recent calls last):
12: install.packages("Matrix")
11: install(pkgs)
10: renv_install_impl(records)
 9: renv_install_staged(records)
 8: renv_install_default(records)
 7: handler(package, renv_install_package(record))
 6: renv_install_package(record)
 5: withCallingHandlers(renv_install_package_impl(record), error = function(e) {
        vwritef("\tFAILED")
        writef(e$output)
    })
 4: renv_install_package_impl(record)
 3: r_cmd_install(package, path)
 2: r_exec_error(package, output, "install", status)
 1: stop(error)

I tried installing Matrix manually, without success.

If that doesn't work, maybe pre-commit is using the global R rather than the local one. This shouldn't happen but would be annoying. In this case, install the packages it's asking about in your global R setup

How do I do that?

**Pull request closed without merging**
